### ISSUE TITLE
Allow container to have a fixed ratio

### ISSUE THREAD

**Issue by jamazerto** [fengyuanchen/cropper#137]
Hi there,
I'm loving the cropper, it does (almost) everything I need. However I was wondering if it would be possible to provide a fixed aspect ratio (in my case it would be the same one as the cropper's) to the container where the image would be displayed centered in 'fit' mode with transparent pixels to fill up on the sides.
This means that the cropper could have negative values for y and x and width and height values above the original image natural width and height.
This isn't exactly an "issue" with the current version but I didn't know where else to put it.

**Comment by fengyuanchen** [comment]
[v0.8.0](https://github.com/fengyuanchen/cropper/releases/tag/v0.8.0) had been released, and it supports this.

**Comment by dejavu1987** [comment]
Hi, I have a question.
I wanted to create a square shape container so I set the container's width and height both 500px, but the cropper increased the container's height according to the ratio of image so that width was 500px and height was dynamically set so I am not able to create exactly square cropper container. I set strict to false, I was able to zoom out but the container was still resized.
Can you point me out where am I going wrong? I am using Cropper v0.9.1
