### ISSUE TITLE
Image size adjusting to the width container

### ISSUE THREAD

**Issue by Lynx12** [fengyuanchen/cropper#245]
The image is adjusting its width to the container width, I think it is wrong, zoomable is disabled. Image should retain its original dimensions.

**Comment by fengyuanchen** [comment]
You should disable the strict mode:

```
$().cropper({
  strict: false
});
```

**Comment by Lynx12** [comment]
But, how could I do to avoid that the crop box goes out of the image boundaries?

**Comment by fengyuanchen** [comment]
You can try to limit it with the provided events.

**Comment by boustanihani** [comment]
@Lynx12 please let us know if you figured out a workaround, same issue here:
https://github.com/fengyuanchen/cropper/issues/238
https://github.com/fengyuanchen/cropper/issues/242

**Comment by marcolz** [comment]
@fengyuanchen I tried limiting it returning `false`, if certain conditions are met, within the `dragmove` callback; but that appears to be too late: at such stage the cropbox/image already moved and I could not figure out a way to roll its position back. Suggestions?

**Comment by marcolz** [comment]
This is my current solution - it currently works for the top and left borders only (I'm still working on right and bottom ones). It's not ideal as it's based on manually moving the cropbox/image back (to a "correct" position) only *after* the border is passed, and therefore a flickering effect is noticeable.

```javascript
    dragmove: function() {
      var $this = $(this);

      var imageData = $this.cropper('getImageData');
      var boxData = $this.cropper('getCropBoxData');

      if (imageData.top > boxData.top) {
        $this.cropper('move', 0, boxData.top - imageData.top);
        return false;
      }

      if (imageData.left > boxData.left) {
        $this.cropper('move', boxData.left - imageData.left, 0);
        return false;
      }
    }
```

**Comment by filipp-qoma** [comment]
I'm working on the same feature)) Sctrict Crop Box))

**Comment by fengyuanchen** [comment]
@marcolz Please use `getCanvasData` and `event.preventDefault()`:

```js
dragmove: function(e) {
  var $this = $(this);
  var canvasData = $this.cropper('getCanvasData');
  var cropBoxData = $this.cropper('getCropBoxData');

  if (canvasData.top > cropBoxData.top || canvasData.left > cropBoxData.left) {
    e.preventDefault();
  }
}
```

**Comment by filipp-qoma** [comment]
@fengyuanchen I'm sorry but it doesn't work (I used `{ strict: false }` if it is metter)
@marcolz's solution works, but cropbox jumps, because cropper triggers "dragmove" event after(!) cropbox was rendered outside the image.
I think the best solution is to check coordinates and sizes and prevent it changing in `change` method. Because user can move either crop box or canvas and cropper has to prevent moving of crop box or canvas depends of what user are moving.
What do you think?

**Comment by marcolz** [comment]
Thank you @fengyuanchen - Unfortunately I cannot use `getCanvasData` because it's broken on 0.8. And I cannot upgrade to 0.9 because something causes the cropper area to stretch to full width:

![screenshot 2015-03-19 10 41 53](https://cloud.githubusercontent.com/assets/20266/6736849/9ecab120-ce24-11e4-856e-031885326d75.png)

I'll keep trying different approaches and keeping you posted.

**Comment by marcolz** [comment]
@filipp-qoma I could not find any `change` method.

**Comment by filipp-qoma** [comment]
@marcolz I'm talking about system changes. I wrote checks of coordinates and sizes of crop box and canvas in `all`, `n`, `w`, `e`, `s` and canvas' `move` cases of `dragmove`. I have to do checks in `crop` and `zoom` cases also and have to place the same checks in `set*` methods and others. I'm doing this for my own project and I'll create a pull request to this repository too.

**Comment by fengyuanchen** [comment]
All right, I will try to improve the strict mode though it is difficult.

**Comment by fgreinus** [comment]
@marcolz Same issue in 0.9.1 for me.
