### ISSUE TITLE
Error on niche usecase for exports with global jQuery

### ISSUE THREAD

**Issue by sofuxro** [fengyuanchen/cropper#348]
I'm using node/commonJS (under browserify) with jQuery loaded as global.
I'm getting an error inside the factory as it enters the 'exports exists' and it's trying to 'require(jQuery)'.

I've solved it by removing the condition and just going with the global (inside the factory function).

You could use 

    function module_exists( name ) {
      try { return require.resolve( name ) }
      catch( e ) { return false }
    }

(resolve - doesn't loads the module just checks if it exists)

... and have something like this

    (function (factory) {
      if (typeof define === 'function' && define.amd) {
        // AMD. Register as anonymous module.
        define(['jquery'], factory);
      } else if (typeof exports === 'object' && module_exists(jQuery)) {
        // Node / CommonJS
        factory(require('jquery'));
      } else {
        // Browser globals.
        factory(jQuery);
      }
    })(function ($) {

PS: thanks for the awesome plugin

**Comment by dantman** [comment]
I think you're going to have more problems than just cropper if you try using browserify but don't make jQuery available through require.

Instead of modifying Cropper. I recommend using either [browserify-shim](https://www.npmjs.com/package/browserify-shim) or [exposify](https://www.npmjs.com/package/exposify) to expose the global jQuery variable as `require('jquery')` to browserify.

**Comment by fengyuanchen** [comment]
@dantman Thank you for answering this issue for me.
