### ISSUE TITLE
large size image returns error on your examples/crop-avatar 

### ISSUE THREAD

**Issue by ls25370** [fengyuanchen/cropper#393]
Hi, I'm using your examples/crop-avatar on my server.

I found there's a problem when I upload large size image (over 3,000px width or height).

It just returns error. I checked server side but it doesn't receive any data from ajax (main.js).

How can I upload over 3,000px images?

**Comment by fengyuanchen** [comment]
Configure the `upload_max_filesize` and `post_max_size` of your `php.ini` file.

**Comment by ls25370** [comment]
both of them are already set 32M and file size is just 1.5MB, any other problem?

**Comment by ls25370** [comment]
It was memory_limit problem on php.ini file. Thank you!

**Comment by ngaugler** [comment]
I too have issues with rather large image sizes.  The file itself is <8MB on disk but when cropper receives the file, even if I make no changes, the filesize within Javascript is over 20MB.  When I try to post this data to a webserver, it takes forever to upload since it's such a big file size, and it also causes issues on the PHP side with limits.  

Attached is an example file that has this problem.  In the demo (http://fengyuanchen.github.io/cropper/) when I upload this file via 'Blob URL' and expand the crop box to the entire image, I cannot download the image via the 'Get Cropped Canvas' feature.


![bad-photo](https://cloud.githubusercontent.com/assets/1454960/11701215/dc03f66a-9e93-11e5-9fd0-a815d60f18dd.jpg)
