### ISSUE TITLE
Safari HTTPS data url cross origin error

### ISSUE THREAD

**Issue by fracsi** [fengyuanchen/cropper#536]
On OSX and iOS Safari if i try to combine cropper with a file uploader (uploading only occurs after submit) on HTTPS, passing the data uri to cropper, the XHR request which transforms the data uri to ArrayBuffer is denied because of the cross-origin policy (only allowed on HTTP).

**Comment by fengyuanchen** [comment]
I see. Do you have any solution for this?

**Comment by shaneparsons** [comment]
This only seem to be a problem with 2.2.0.
I updated to 2.2.0 yesterday and was having this issue until I reverted back to 2.1.0.

**Comment by fengyuanchen** [comment]
You need to set the response header `Access-Control-Allow-Origin: *`.

**Comment by fracsi** [comment]
@fengyuanchen 
As i stated in the original question, i'm passing a data uri to cropper (data:image/jpeg;base64...), so i cannot set any response header, because there is no response. This is a Safari limitation for loading a data uri through ajax. In your code you use ajax to transform the image to ArrayBuffer.

**Comment by fengyuanchen** [comment]
Okay~ I have no solution yet. You might need to set the `checkOrientation` to `false`.

**Comment by fengyuanchen** [comment]
Okay~ I have no solution yet. You might need to set the `checkOrientation` to `false`.

**Comment by fracsi** [comment]
Can't you use a canvas instead of ajax to convert the image to ArrayBuffer?
Something like: `someCanvasElement.getContext('2d').getImageData(0, 0, width, height).data.buffer` ?

**Comment by fengyuanchen** [comment]
No, there are more issues with a canvas in Safari, see #120, #509.

**Comment by fengyuanchen** [comment]
@fracsi How about use a blob url (`URL.createObjectURL(file)`)?

**Comment by fengyuanchen** [comment]
Please update to the v2.2.1.

**Comment by michael-go** [comment]
I believe I just had the same issue on an older Chrome 37
when creating `$(myImg).cropeer()` on an image whose source is a data-url, i got the following CORS error: 
`XMLHttpRequest cannot load data:image/png;base64,.... Received an invalid response. Origin '...' is therefore not allowed access.`

The issue was solved by using `URL.createObjectURL()` instead of the data-url as you suggested. 

This worked for me because I originally got the data-url using a FileReader() which means I had a `file` object. However if someone has only a data-url to work with, I think it is still possible to make it work, however requires changing the code of cropper.js:  **avoiding** setting `crossOrigin="anonymous"` on Safari specifically. (In the past I stumbled upon a similar issue on iPhone's Safari, and that solved it)

Thanks,
and b.t.w, Cropper.js is great :smiley:

**Comment by fengyuanchen** [comment]
@michael-go You can try the latest version (v2.2.1), it doesn't load Data URL by `XMLHttpRequest` any more.

**Comment by michael-go** [comment]
@fengyuanchen This was the first thing I tried, but it didn't help in my case - I double-checked it now and still get the error with Data URL.
Thanks

**Comment by fracsi** [comment]
@fengyuanchen 
Can you update the dist versions also? I installed cropper with bower, and in version 2.2.1 the dist directory contains 2.2.0 files.

**Comment by qiankaijie** [comment]
哥们，2.2.1没更新到位呀！ 最新文件还是2.2.0的

**Comment by fengyuanchen** [comment]
@fracsi @qiankaijie Sorry~ I forgot to submit the release files...It's done now.
