### ISSUE TITLE
Support Circular shaped cropping

### ISSUE THREAD

**Issue by anuja-joshi** [fengyuanchen/cropper#568]
Many times we need to crop image in circular shape, we can add an option in this plugin say `shape` which will be `square/rectangle` by default but can be `circle`.

Let me know, your thoughts on this. If you find this useful, I will work on this.

**Comment by fengyuanchen** [comment]
Refer to #382 and #545 please.

**Comment by anuja-joshi** [comment]
@fengyuanchen yes, you are right. Overriding `.cropper-crop-box` and `.cropper-view-box` with `border-radius` will work, but why not to provide this as an option? what if we add a new class(with `border-radius` property) and apply this class if option `shape` is set as `circle` by users?

**Comment by fengyuanchen** [comment]
Thanks for your suggestion, but I think it is not a very necessary feature, and in order to keep this plugin simple, I think it may be better to let the users to customize it when they need this feature. 

In addition, I have added an example for reference: [Crop a round image](https://github.com/fengyuanchen/cropper/blob/master/examples/crop-a-round-image.html)

**Comment by KielD-01** [comment]
@fengyuanchen , I think, that You should add this feature because quite often circle image is needed instead of a rectangle

**Comment by VishalTennyson** [comment]
Is there a way I can use non rectangle shapes like Parallelogram such that the cropping is more free style?
