### ISSUE TITLE
Getting transparent image on IPhone

### ISSUE THREAD

**Issue by kazantip151** [fengyuanchen/cropper#577]
Hi, on iphone, i`m getting transparent image instead normal image..
I`m doing some check with width of picture :

``` javascript
var imageData = $('.box-wrap > img').cropper('getImageData');

                  if(imageData.naturalWidth > 960)
                  {
                     var $canvas = $('.box-wrap > img').cropper('getCroppedCanvas', {width: 960});
                  }else{
                    var $canvas = $('.box-wrap > img').cropper('getCroppedCanvas');
                  }

```

and this getting me transparent image with width 960px on IPhone

**Comment by gdsdougherty** [comment]
I seem to be getting the same thing, IOS9 seems to work, but not on ios 8 or 7 phones.  IOS 8 also seems to work on the ipad air 2.  I'm trying to figure out the issue myself, I am also sending in the width through there as you are.

**Comment by gdsdougherty** [comment]
Removing the width seemed to fix it, unfortunately this could be problematic, especially when using the width is actually required.

**Comment by gdsdougherty** [comment]
http://stackoverflow.com/questions/26152652/ios-html5-canvas-todataurl

After inspecting in browser using browserstack, it turns out it's returning data; when the image is too large at times.  It turns out if you use larger than a 3 megapixel canvas (on 256 or less mb ram devices), or 5 megapixels on larger ram devices, it returns a blank data canvas or blank data url.  When you  force a height / width it forces a blank all white image as a data url.  If you view the data url, it, in my case, repeated the string CAAQMGDBgwYM, I'm assuming means a single white pixel.

Ironically, this 5 megapixel limit means they don't support photos taken by their own phones.  I haven't been seeing this issue with IOS 9, but it's entirely possible they updated the requirements some.  Not sure of an actual solution to this one, other than asking users to use a real phone, or reduce the size beforehand.

**Comment by fengyuanchen** [comment]
iOS resource limits is a [known issue](https://github.com/fengyuanchen/cropper#known-issues), see #294.

**Comment by kazantip151** [comment]
@gdsdougherty  thx for your comments. @fengyuanchen so thats what i`m doing like in issue #294. i make picture little than 1000px.

**Comment by ndtreviv** [comment]
We can't downsize the image because we used the cropped image for print. I've identified and am working on a fix for this.
