### ISSUE TITLE
MVC

### ISSUE THREAD

**Issue by Antquity** [fengyuanchen/cropper#610]
Does anyone have any samples on how to send the cropped image from the client through ajax to an MVC controller.  Seems this would be reasonably easy but i just cant figure it out 
Not in PHP but in c#

**Comment by fengyuanchen** [comment]
It seems nobody answer this. I suggest you to ask help on the StackOverflow.

**Comment by chtay1** [comment]
Here is a simple MVC action that can consume a DataURL version of the canvas from a cropper instance (or infact any DataURL). As this is base64 encoded it will add size to the transfer over a binary representation so you should consider whether this appropriate for your usage.

[HttpPost]
public async Task<ActionResult> UploadImageAsync(string imageData)
{
    if (string.IsNullOrEmpty(imageData))
        throw new ArgumentNullException(nameof(imageData), "No image data received");

    Match imageMatch = Regex.Match(imageData, @"^data:(?<mimetype>[^;]+);base64,(?<data>.+)$");
    if (!imageMatch.Success)
        throw new ArgumentException("imageData is in unknown format", nameof(imageData));

    string mimeType = imageMatch.Groups["mimetype"].Value;
    Match imageType = Regex.Match(mimeType, @"^[^/]+/(?<type>.+?)$");
    if (!imageType.Success)
        throw new ArgumentException($"mimeType format invalid for {mimeType}", nameof(mimeType));

    string fileExtension = imageType.Groups["type"].Value;
    byte[] data = Convert.FromBase64String(imageMatch.Groups["data"].Value);

    // Do something with your binary image data
}

javascript:

var imageDate = $("#yourCropper").cropper("getCroppedCanvas", canvasSize).toDataURL();

$.ajax({
    url: '/Image/UploadImageAsync/',
    type: 'POST',
    data: { 'imageData': imageData },
    dataType: 'json',
    timeout: 300000
});

**Comment by Antquity** [comment]
Thanks for that , how do i get the canvas size ?

**Comment by chtay1** [comment]
Sorry, set canvasSize to the width and height you require e.g. 

canvasSize = { width: 800, height: 600 };

**Comment by Antquity** [comment]
OK so now i have 
      
var canvasSize = { width: 200, height: 200 };
var imageData = $("#crop-avatar").cropper("getCroppedCanvas", canvasSize).toDataURL();

and I get

TypeError: $(...).cropper(...).toDataURL is not a function

Im doing this in Modal

**Comment by SoundLogic** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL

**Comment by Antquity** [comment]
Thanks for that , will give it a go
I see there is also a function getCroppedCanvas , can this be used to post the cropped image to an api? , Sorry but still struggling a little with using the script

**Comment by SoundLogic** [comment]
`$('#myimage').cropper('getCroppedCanvas')` is going to return an `HTMLCanvasElement` where the cropped image is essentially "painted" on the canvas element. The `toDataURL` method is a standard method which should be available in any of the latest popular browsers (not part of the cropper library) and should convert the canvas element into a base64 encoded representation of your image (note it defaults to png so if you expect your users to be uploading photographs instead of images with text in them you'll probably want to use the "image/jpeg" mime type  - the link I provided above provides clear details on this). 

The data url is your image and you can safely post it to your API as @chtay1 demonstrated. You can then pull that data url, as a string, from your backend and use it as the source of your image tag as demonstrated here: https://css-tricks.com/data-uris/. In some rare cases you may be working with a legacy API which already accepts an image - perhaps you're still supporting older browsers that do not support `HTMLCanvasElement` and you have a method which uploads an image using a Form. If you can avoid this I would suggest it because you're going to end up sending bigger payloads across the wire, but if you absolutely must you can convert the data url to a blob and post it as Form data. If you need to do this (and again I would suggest you do not) I can provide you with an explanation of how to do this if you put the question on stack overflow :smiley: 

@fengyuanchen has provided some great example code and I was able to figure almost everything out to get up and running with the docs and by understanding the sample code - I would suggest looking at the sample code and getting a good understanding of it.

**Comment by Antquity** [comment]
Your time and patience appreciated , yes @fengyuanchen has supplied some great code vut the key part of the avatar sample is php and im doing this in mvc so im struggling with getting this to work , will look at what you have suggested and see if i can get a working model, cheers

**Comment by SoundLogic** [comment]
okay well keep in mind that you can also just have a look at the [source code](https://github.com/fengyuanchen/cropper/tree/master/demo) for the [demo page](http://fengyuanchen.github.io/cropper/) which doesn't use php at all. You can reverse engineer that by looking at how the button events are wired up to the rest of the code. You should have everything you need to create an avatar image with plain old javascript and html. You can setup an aspect ratio when you setup Cropper, Cropper's `getCroppedCanvas` method allows you to pass in an optional width and height (which should of course be proportional to your aspect ratio if you set that) and the `toDataURL` method allows you to set the image compression/quality so you can ensure the avatar is lightweight and loads quickly.

**Comment by Antquity** [comment]
yes thats what im trying to do , but im preyty much a javascript newbie, so im unsure where the changes need to be in the main.js or on my page neither work for me at this stage

**Comment by Antquity** [comment]
After working with what was described  this is what i have which is working and displays the cropped back in the same page

    $('#btnCroped').click(function () {


        var croppedCanvas;
        var $image = $('.avatar-wrapper > img');

        var canvasSize = { width: 200, height: 200 };
        var imageData = $image.cropper("getCroppedCanvas", canvasSize).toDataURL();
        croppedCanvas = $image.cropper('getCroppedCanvas');
        var $avatarPreview = $('.preview-new ');
        $avatarPreview.html('<img src="' + croppedCanvas.toDataURL() + '">');
    });

But of i use ajax to post it back it doesnt seem to recognise the string 


   var croppedCanvas;
            var $image = $('.avatar-wrapper > img');
            var canvasSize = { width: 200, height: 200 };
            var imageData = $image.cropper("getCroppedCanvas", canvasSize).toDataURL();

            var url = this.$avatarForm.attr('action');

            var dataToPost = "{ url:'" + url + "', data:" + imageData + "}";

            $.ajax(url, {
                type: 'post',
                data: dataToPost,
                dataType: 'json',
                processData: false,
                cache: false,
                contentType: "application/json; charset=utf-8",

**Comment by Antquity** [comment]
The controller starts like this 

public void SaveAvatar(string url, string imageData)

**Comment by chwanyoung** [comment]
$("#saveImage").click(function () {


    
    var imageData = $image.cropper("getDataURL");

$.ajax({
    url: '/Helper/UploadImageAsync/',
    type: 'POST',
    data: { 'imageData': imageData },
    dataType: 'json',
    timeout: 120000,
    success: function (response) {

    },
    error: function (e) {
        
    },
    complete: function () {

    }
});
});
