### ISSUE TITLE
Not loading proper dimensions inside a bootstrap tab

### ISSUE THREAD

**Issue by Evangelion86** [fengyuanchen/cropper#642]
First of all, thank you very much for your work; it's amazing and it's really helping my work. During the last 2 days I've been trying to figure out how to solve an issue I'm experiencing and I ended up with the solution of trying a direct question to you.
Thank you very much if you'll have a few time to spare your ideas about it.

Issue:

I'm using bootstrap.
I've a page where i inserted your code and it's divided into tabs. The first tab is a sort of "home-page-tab" and the resizer is inserted inside another one.

If I put your code inside the first tab, it works perfectly, but if I put it inside a not first loading tab, it's not visible till i resize the window. After I resize the browser, it works. In the not 1st loaded tab it gets the mincontainer width&height and not the one from the page dimension.

Hope to hearing from you soon. :)

**Comment by SoundLogic** [comment]
Could you provide some code? Are you using just plain html/css/js + bootstrap or are you using a framework like Angular. I have a hunch what the idea is if you're using angular, but again code would really help.

**Comment by Evangelion86** [comment]
Thank you for the quick reply.
I'm not using angular js.

I've set the page online so you can read the code: http://massimilianoronchetti.it/issue/dashboard-professionisti.html

When you click on the tab "Vetrina Dettaglio" the ".cropper-container" div hasn't the dimensions of its container.
If I resize the window's browser, it works.

Thank you again!

**Comment by jensens** [comment]
I have the same problem here, no bootstrap but own tab code, but it does not matter that much.

I use tabs on top to show the different image fields I have and kind of tabs aside to for the different scales each image should be cropped to. See 
![screenshot-localhost 8080 2016-03-25 13-37-58](https://cloud.githubusercontent.com/assets/157140/14044279/e6e2eec0-f28e-11e5-9489-682f28fada6b.png)
creenshot.

First, in order to make cropper happy, I need to have the area it is loaded in visible. In my case i load cropper and then jquery ``.hide()`` the areas. This flickers a bit but does not hurt much. 

Second after I click on a tab and it gets visible I need to trigger cropper's ``.resize()``. 

I don't know if it helps much, but the code is here: 
https://github.com/collective/plone.app.imagecropping/tree/imagecrop-pattern-and-plone-5/src/plone/app/imagecropping/browser/static

**Comment by fengyuanchen** [comment]
@Evangelion86 and @jensens, please start to initialize a cropper only when the target tab content is shown completely!

**Comment by jensens** [comment]
yeah, what about a short note in the docs about it? it took me quite some time to figure this out. this is not obvious at the first place. it is further more valid for the preview area as well.

**Comment by fengyuanchen** [comment]
@jensens See the first note: https://github.com/fengyuanchen/cropper#notes

**Comment by Evangelion86** [comment]
Thanks @fengyuanchen, have a nice day!
