### ISSUE TITLE
Enhancement: Minimum cropped aspect ratio

### ISSUE THREAD

**Issue by zilions** [fengyuanchen/cropper#659]
This would be a great enhancement that I believe many users would appreciate. Currently, there are options for `minCropBoxWidth` and `minCropBoxHeight`. What if we could have an option such as `minAspectRatio` that allows us to set a minimum aspect ratio that users can crop their image to. I currently have both `minCropBoxWidth` and `minCropBoxHeight` set to 50, although that does not stop a user from creating an image that is 1000x50...

I have the problem that users can make a very skinny image (1000x50), or very tall image (50x1000), hence destroying the layout of the website. It would be great to set a minimum aspect ratio so that users can only set images at 1/2 or 2/1 for example, therefore not messing up my interface too much.

**Comment by fengyuanchen** [comment]
Please reference this example: [Cropper with a range of aspect ratio](https://github.com/fengyuanchen/cropper/blob/master/examples/a-range-of-aspect-ratio.html)

**Comment by chaoaretasty** [comment]
@fengyuanchen  I've been looking at trying to implement min/max aspect ratio and I would like to request reopening this issue.

I looked at the example given and there's a significant problem. Up until reaching the boundary of an aspect ratio it works fine but after dragging past a boundary the crop box resizes based on mouse movements and not mouse position.

I dug a bit deeper into the code and the problem is that a set aspectRatio has specific handling of its values before the change is applied, this logic is not replicated in the bounded aspet ratio example and arguably cannot be easily (for instance settings `renderable = false` and skipping over `renderCropBox()).
