### ISSUE TITLE
getCroppedCanvas should not fail when not cropping.

### ISSUE THREAD

**Issue by wcatron** [fengyuanchen/cropper#666]
If you call `.cropper("clear");` and then call `.cropper('getCroppedCanvas')` you don't get a canvas. Now I understand if I had destroyed the cropper that yes `getCroppedCanvas` should fail. However clear should just clear the cropping feature (I have a button where the user can toggle this on or off). You can achieve a similar issue if you go to the [demo](http://fengyuanchen.github.io/cropper/) site and click the "clear" button and then the "getCroppedCanvas" no image shows up. I really think this should display the entire image in the canvas completely un-cropped.

I previously wrote about the issue in #624 but further testing revealed this more systemic problem.

Example errors when this is happening:

Microsoft

> TypeError: Object doesn't support property or method 'toDataURL'

Firefox on Windows

> TypeError: $modal.find(...).cropper(...).toDataURL is not a function

Safari on Mac

> TypeError: $modal.find('.upload-image').cropper('getCroppedCanvas').toDataURL is not a function. (In '$modal.find('.upload-image').cropper('getCroppedCanvas').toDataURL()', '$modal.find('.upload-image').cropper('getCroppedCanvas').toDataURL' is undefined)

**Comment by vinnymac** [comment]
The name of the function `getCroppedCanvas` implies retrieval of a cropped canvas. If the canvas is not being cropped perhaps another method should exist with the name `getCanvas`. It could return the entire un-cropped canvas. Their is the utility method `getSourceCanvas`, if this ticket gets resolved I imagine it would be used to return the canvas you are looking for. Here are some helpful solutions.

You can just [draw it](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage) yourself:

```javascript
function getCanvas($image) {
  var canvas = $image.cropper("getCroppedCanvas");

  if (canvas instanceof HTMLCanvasElement) {
    return canvas;
  } else if (canvas[0] instanceof HTMLImageElement) {
    // drawImage to canvas, return the canvas
  }
}
```

Or you could fork cropper and modify it [here](https://github.com/fengyuanchen/cropper/blob/cff5371fef188b2f1b2dac926fe1f95c7b77d50b/src/js/methods.js#L629) like so:
```javascript
if (!this.isBuilt || !SUPPORT_CANVAS) {
  return;
}

if (!this.isCropped) {
  return getSourceCanvas(this.$clone[0], this.image);
}
```

**Comment by wcatron** [comment]
Ah! The 'getSourceCanvas' may work. I understand the name implies the cropped canvas but it is cropped it's just cropped to 0,0,width,hieght. It just makes sense that you should be able to call one function to get the image as the user cropped it. The 'getCanvas' function might be a good middle ground, however it *doesn't* imply being cropped, so still potential confusion. I'll put together that fork from your code and try it.

**Comment by vinnymac** [comment]
I understand what you are saying, but I don't think this lib was built with that behavior in mind. If you click `getData` in the demo after clearing, you can see it returns data like you describe above. However if you click `getCropBoxData` after clearing, it returns an empty object.

Clear removes the crop box, which implies you are no longer "cropping". It also sets the `this.isCropped = false` flag.

It may be convenient to have this work the way you describe, but it might be even better if one could just retrieve the current canvas whether or not the user was cropping. If we wanted to be flexible we could expose both `isCropped` and `getSourceCanvas`. Instead of changing the current API or adding new methods, this just exposes existing functionality. An example of what I am describing is below. 

```javascript
function getCanvas($image) {
  if ($image.cropper("isCropped")) {
    return $image.cropper("getCroppedCanvas");
  } else {
    return $image.cropper("getSourceCanvas");
  }
}
```
