### ISSUE TITLE
Zoom image to constrain on rotate

### ISSUE THREAD

**Issue by ndtreviv** [fengyuanchen/cropper#685]
Is it possible to constrain the canvas to the cropbox size when rotating?

eg: Currently, when you rotate 90 deg, the corners of the cropbox overflow the canvas. I'd like it so that the image is automatically zoomed so that the corners are covered (a la oddprints.com).

Is that possible? If not, can it be a new feature?! ;)

**Comment by ndtreviv** [comment]
Sorry, I mean't 45 degrees. Obviously with viewMode 1 the canvas zooms to contain the cropBox when rotated 90 degrees, but at 45 degrees no zooming happens, which means that the cropBox is not contained by the canvas in its entirety.

**Comment by ndtreviv** [comment]
Alternatively, it might be easier to offer a viewMode where the cropbox resizes to be contained by the canvas. This would ensure that the user can always see the whole image. I hope this makes sense!

**Comment by ndtreviv** [comment]
I've worked around this by listening for the crop event and resizing the canvas when rotating.

**Comment by JAndritsch** [comment]
@ndtreviv I'm attempting to do something similar, in that when an image is rotated the crop box corners end up staying contained within the rotated image so there are no blank pixels ever captured in the crop box.

An example of what I'm after can be seen here: https://creativesdk.github.io/web-image-editor-drag-and-drop/. Select an image, then go to the "Orientation" view and drag the slider at the top of the image to the right or left. You'll notice that the crop box stays within the boundaries of the rotated image due to zooming.

Is this what you solved, and if so, would you be willing to share a sample of the code you used to do that?

Thanks!

**Comment by ndtreviv** [comment]
@JAndritsch Sure - I ended up forking this project and implementing it as a new viewMode. You can find it here: https://github.com/OddPrints/cropper

It's not been massively tested for all possible options - we're using it for a very specific purpose. To see it in action, go to: https://www.oddprints.com

Note: When you rotate, the cropBox resizes down so that it always fits inside the rotated image, but it doesn't resize back up again (because it doesn't know if it resized down due to a rotation, or due to user action).

Have a play. I hope it helps. 

Cheers!

**Comment by JAndritsch** [comment]
@ndtreviv Awesome. Thanks for your help!

**Comment by cybersholt** [comment]
@ndtreviv Thanks, any chance of updating to the latest? It would be nice to have this in the official lib too.

**Comment by ndtreviv** [comment]
> @ndtreviv Thanks, any chance of updating to the latest? 

Not really any time soon. I'm not working on that project anymore. Next time I do any frontend work it'll likely be to re-do the entire thing in React or similar. At that point I'm not sure whether this cropper would still be appropriate.

The latest master has changed so much, I'm just not sure that it's worth my time fighting a never ending update battle.

> It would be nice to have this in the official lib too.

It would, but alas, it has been rejected by the maintainer.
