### ISSUE TITLE
Touch-Scrolling on iOS

### ISSUE THREAD

**Issue by ktrhn** [fengyuanchen/cropper#703]
Great Plugin!

I am trying to enable touch-scrolling on the cropper container. I only allow moving of the crop area and would like users to be able to scroll while making scroll/touchmoves on the rest of the container. This works just fine for scroll events on desktop but not for touch events on mobile (I tested iOS/Safari). I "emulated" scrolling by using the cropper events, but I am losing the "-webkit-overflow-scrolling: touch" effect and scrolling does not feel so "natural". Any way to prevent cropper fetching the events or to allow propagating the touch events? 

Here my code so far (modal is the scrollable container).

````
$imageTag.cropper({
    dragMode: 'none',
    movable: false,
    viewMode: 3,
    zoomable: false
});

let touchstart = null;
$imageTag.on('cropstart.cropper', (event) => {
    if ('none' === event.action && 'touchstart' === event.originalEvent.type) {
        touchstart = event.originalEvent.pageY;
    }
});
$imageTag.on('cropmove.cropper', (event) => {
    if ('none' === event.action && 'touchmove' === event.originalEvent.type && null !== touchstart) {
        modal.scrollTop += (touchstart - event.originalEvent.pageY);
        touchstart = event.originalEvent.pageY;
    }
});
$imageTag.on('cropend.cropper', (event) => {
    if ('none' === event.action && 'touchend' === event.originalEvent.type && null !== touchstart) {
        modal.scrollTop += (touchstart - event.originalEvent.pageY);
        touchstart = null;
    }
});
````

**Comment by fengyuanchen** [comment]
Sorry, I have not idea on this.

**Comment by ndtreviv** [comment]
Isn't this the same as #727?

On that issue you ( @fengyuanchen ) asked if I had really solved it. My fix did indeed solve it for me.

My issue was that I couldn't scroll the page when swiping on the container when `dragMode` was set to `none`. Same as @ktrhn , unless I'm misunderstanding it?

ie:
 
* Touch drag the cropbox should move the cropbox.
* Touch drag the container should scroll the page.
 
I found the problem was that the swipe-to-scroll touch event was being swallowed up by an `e.preventDefault()` even though the action was `ACTION_NONE`.

@ktrhn - Take a look at #727 and try implementing the fix on my fork in your local copy to see if it solves it for you.

**Comment by ktrhn** [comment]
Yes, it is the same Problem and the fix of @ndtreviv solves it :-)
So 👍 for a merge @fengyuanchen

**Comment by fengyuanchen** [comment]
@ktrhn Please try the latest version (v2.3.3).
