### ISSUE TITLE
Avoid cropbox image overflow

### ISSUE THREAD

**Issue by luchorengo** [fengyuanchen/cropper#772]
Hi Folks,

Just wondering if there is a way to avoid image overflow in cropbox. I'd like to see only what it fits in blue bordered square and hide everything else.
I'm using **modal: false** and **background: false** but no luck, the image overflows the crop area.
I guess that it's about cropper-container size but I'm not sure how to handle this.

Thanks in advance

**Comment by fengyuanchen** [comment]
Try this:
```js
$().cropper({
  autoCropArea: 1,
  movable: false,
  zoomable: false,
  rotatable: false,
  scalable: false,
});
```

**Comment by artuska** [comment]
@fengyuanchen no, it does not work. Just check it yourself — go to the https://fengyuanchen.github.io/cropper/, click 2 times on the `rotate left` button — image will be cut on top and bottom (on left and right originally). Emma's shadow will go outside the cropper boundaries — because image is not resized proportionally after rotate. And if I use `VM1` and `Free` aspect ratio and crop the whole available image after the rotate, the crop data will be wrong, because parts of the image are outside the cropper boundaries.
