### ISSUE TITLE
Zoom does not work anymore with Chrome on Android devices

### ISSUE THREAD

**Issue by JSteunou** [fengyuanchen/cropper#827]
on Android 6.0 with Chrome 55

When zooming even just a tiny pixel it just unzooms way to much and the image & the cropper disappear.

Tested and reproduced with all your examples.

**Comment by greatmemar** [comment]
Same issue here... When I zoom in or zoom out, it totally disappear...

**Comment by fengyuanchen** [comment]
As of version 55, Chrome starts to support [Pointer Events](http://caniuse.com/#feat=pointer) which causes this problem. I will resolved this soon.

**Comment by fengyuanchen** [comment]
I cannot fixed this right now, recommend to use the non-jQuery version as this issue had been fixed in that.

> - [Cropper.js](https://github.com/fengyuanchen/cropperjs) - the non-jQuery version of Cropper (**recommended**).

**Comment by fengyuanchen** [comment]
This has been fixed in v3.0.0-alpha.

**Comment by JSteunou** [comment]
For those who cannot already migrate to cropper.js and just want a quick fix you can still use this one at this commit 5d9560e84dd49249eb98e873d322e122641aaa32

**Comment by RByers** [comment]
Sorry for the trouble, this is a breaking change in Chrome 56 to [improve scroll performance](https://developers.google.com/web/updates/2017/01/scrolling-intervention).  This can probably also be fixed by adding an appropriate `touch-action` [CSS rule](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action) to disable the browser's own scrolling/zooming.

**Comment by JSteunou** [comment]
That's why I was pointing out the commit 5d9560e as a nice v2.3.5 substitute. If you look closely you will find that previous commits include a fix for pointer event **and** `touch-action: none;`
