### ISSUE TITLE
Part of image pushed outside container after rotating 360 degrees

### ISSUE THREAD

**Issue by DePalmo** [fengyuanchen/cropper#931]
OS: Windows 7 SP1 Ultimate x64
Browser: Chrome 61.0.3163.100 64bit
Test case: https://jsbin.com/mukohebebo/edit?html,output
How to replicate the issue:
- open link above
- expand cropping so it will touch upper and lower container border
- rotate image full 360 degrees in any way
- look at left / right border, you will notice that image is pushed off screen

This issue only happens when cropping tool is expanded, if it does not touch borders the issue is not present.

**Comment by fengyuanchen** [comment]
Bug of Chrome? Please upgrade to Chrome v62 and try again.

**Comment by DePalmo** [comment]
Updated Chrome to 62.0.3202.62, issue is still present. I also tried IE11 and Firefox, versions are in screenshots.

![2017-10-26 19-41 image 001](https://user-images.githubusercontent.com/3665779/32068205-ee047f8c-ba85-11e7-96af-ee9da36e0ab9.jpg)
![2017-10-26 19-41 image 002](https://user-images.githubusercontent.com/3665779/32068185-dd5d5db6-ba85-11e7-8606-5d5b9cdaaf03.jpg)
![2017-10-26 19-40 image 002](https://user-images.githubusercontent.com/3665779/32068189-df732a22-ba85-11e7-863e-d869d9faab44.jpg)

**Comment by fengyuanchen** [comment]
Because the viewMode is `1` and the crop box is not centered:

1. Move the crop box to left with 10px offset.
1. Rotate 90°.
1. In order to fit view mode restrictions, the image will move left 10px automatically too.
1. Rotate 90°.
1. You can see the image has 10px offset now.

Keep the crop box **center** absolutely, you will not run into this issue. 

Another solution:

```js
$('#jcrop')
  .cropper('clear')
  .cropper('rotate', 90)
  .cropper('crop');
```
