### ISSUE TITLE
Cropper - Angular 5

### ISSUE THREAD

**Issue by DaoFof** [fengyuanchen/cropper#986]
Can we use Cropper with angular 5?
If yes a demo is welcomed!

**Comment by messerbill** [comment]
Since cropper is based on https://github.com/fengyuanchen/cropperjs/ which is written in JavaScript you should easily be able to make an angular implementation of it. You could simply build an angular component which makes an instance of the cropper and you can give the config properties to the cropper library via `@Input()` variables to the component for example.
